version: '3.8'

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - metrics-network

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    networks:
      - metrics-network
    volumes:
      - influxdb-data:/var/lib/influxdb

networks:
  metrics-network:
    driver: bridge
